begin;
do $$
declare h jsonb; h2 jsonb; p jsonb; hd jsonb; pd jsonb; vd jsonb; s jsonb; points int; calls int;
begin
 h:=public.cervellone_api('create','{"title":"SQL TEST"}','sql-verification');
 assert h->>'error' is null,h::text;
 hd:=jsonb_build_object('pin',h->>'pin','secret',h->>'secret','role','host');
 vd:=jsonb_build_object('pin',h->>'pin','role','display');
 p:=public.cervellone_api('join',vd||'{"name":"SQL Player"}','sql-verification');
 assert p->>'error' is null,p::text;
 pd:=jsonb_build_object('pin',h->>'pin','secret',p->>'secret','role','player');
 s:=public.cervellone_api('join',vd||'{"name":"sql player"}','sql-verification');assert s->>'error' is not null;
 s:=public.cervellone_api('host',vd||'{"command":"start"}','sql-verification');assert s->>'error' is not null;
 s:=public.cervellone_api('state',vd||'{"role":"host"}','sql-verification');assert s->>'error' is not null;
 s:=public.cervellone_api('state',vd,'sql-verification');assert s->'questions'='null'::jsonb;
 s:=public.cervellone_api('host',hd||'{"command":"upload","questions":[{"question":"test","options":["A","B","C","D"],"correctIndex":9}]}','sql-verification');assert s->>'error' is not null;
 s:=public.cervellone_api('host',hd||'{"command":"upload","questions":[{"question":"Test 1","options":["A","B","C","D"],"correctIndex":0},{"question":"Test 2","options":["A","B","C","D"],"correctIndex":1}]}','sql-verification');assert s->>'error' is null,s::text;
 s:=public.cervellone_api('host',hd||'{"command":"settings","duration":90,"autoAdvance":false,"freeSkips":0,"penalty":200}','sql-verification');assert s->>'error' is null,s::text;
 s:=public.cervellone_api('host',hd||'{"command":"start"}','sql-verification');assert s->>'phase'='precount',s::text;
 s:=public.cervellone_api('host',hd||'{"command":"start"}','sql-verification');assert s->>'error' is not null;
 update cervellone_private.rooms set deadline=clock_timestamp()-interval '0.1 seconds' where pin=h->>'pin';
 s:=public.cervellone_api('state',vd,'sql-verification');assert s->>'phase'='question',s::text;assert not(s->'question'?'correctIndex');
 s:=public.cervellone_api('state',pd,'sql-verification');assert s->'question'='null'::jsonb;
 s:=public.cervellone_api('answer',pd||jsonb_build_object('idx',0,'round',s->'round','choice',0),'sql-verification');assert s->'mine'->>'choice'='0',s::text;
 s:=public.cervellone_api('answer',pd||jsonb_build_object('idx',0,'round',s->'round','choice',1),'sql-verification');assert s->'mine'->>'choice'='0';
 s:=public.cervellone_api('join',pd||'{"name":"changed"}','sql-verification');assert s->>'name'='SQL Player';
 s:=public.cervellone_api('join',vd||'{"name":"late"}','sql-verification');assert s->>'error' is not null;
 s:=public.cervellone_api('host',hd||'{"command":"reveal"}','sql-verification');assert s->>'error' is null,s::text;points:=(s->'board'->0->>'score')::int;assert points between 780 and 1300;
 s:=public.cervellone_api('host',hd||'{"command":"reveal"}','sql-verification');assert s->>'error' is not null;
 s:=public.cervellone_api('state',pd,'sql-verification');assert (s->'mine'->>'score')::int=points and s->'mine'->>'result'='correct';
 s:=public.cervellone_api('host',hd||'{"command":"next"}','sql-verification');assert s->>'phase'='precount';
 update cervellone_private.rooms set deadline=clock_timestamp()-interval '0.1 seconds' where pin=h->>'pin';
 s:=public.cervellone_api('state',pd,'sql-verification');assert s->>'phase'='question';
 s:=public.cervellone_api('answer',pd||jsonb_build_object('idx',0,'round',s->'round','choice',1),'sql-verification');assert s->>'error' is not null;
 update cervellone_private.rooms set deadline=clock_timestamp()-interval '0.1 seconds' where pin=h->>'pin';
 s:=public.cervellone_api('state',pd,'sql-verification');assert s->>'phase'='reveal';assert s->'mine'->>'result'='missed';assert (s->'mine'->>'score')::int=points-200;
 s:=public.cervellone_api('answer',pd||jsonb_build_object('idx',1,'round',s->'round','choice',1),'sql-verification');assert s->>'error' is not null;
 s:=public.cervellone_api('host',hd||'{"command":"next"}','sql-verification');assert s->>'phase'='final';
 s:=public.cervellone_api('host',hd||'{"command":"reset"}','sql-verification');assert s->>'phase'='lobby' and s->'board'->0->>'score'='0';
 h2:=public.cervellone_api('create','{"title":"ISOLATION TEST"}','sql-verification');
 s:=public.cervellone_api('host',jsonb_build_object('pin',h2->>'pin','role','host','secret',h->>'secret','command','end'),'sql-verification');assert s->>'error' is not null;
 s:=public.cervellone_api('host',hd||'{"command":"settings","autoAdvance":true}','sql-verification');
 s:=public.cervellone_api('host',hd||'{"command":"start"}','sql-verification');
 update cervellone_private.rooms set deadline=clock_timestamp()-interval '0.1 seconds' where pin=h->>'pin';
 s:=public.cervellone_api('state',pd,'sql-verification');assert s->>'phase'='question';
 s:=public.cervellone_api('host',hd||'{"command":"reveal"}','sql-verification');
 update cervellone_private.rooms set deadline=clock_timestamp()-interval '0.1 seconds' where pin=h->>'pin';
 s:=public.cervellone_api('state',pd,'sql-verification');assert s->>'phase'='precount' and s->>'idx'='1';
 select count into calls from cervellone_private.limits where bucket='host:sql-verification';assert calls>12;
 assert not has_function_privilege('anon','public.cervellone_api(text,jsonb,text)','EXECUTE');
 assert not has_function_privilege('authenticated','public.cervellone_api(text,jsonb,text)','EXECUTE');
 assert not has_schema_privilege('anon','cervellone_private','USAGE');
 raise notice 'PASS: all database invariants';
end $$;
rollback;
select 'PASS: permissions, isolation, validation, deadlines, exactly-once scoring, reconnect, auto advance, reset and limits' as result;
